### ISSUE TITLE
Serving of docs is broken

### ISSUE THREAD

**Issue by EdricChan03** [crafted/crafted#97]
Currently, when attempting to run `ng serve docs` on the root of the project, I get the following error:

```
ERROR in projects/docs/src/app/demo-dashboard/demo-dashboard.ts(9,9): error TS2305: Module '"../../../../../dist/data/crafted-data"' has no exported member 'DataResources'.
projects/docs/src/app/demo-dashboard/demo-dashboard.ts(27,3): error TS2741: Property 'id' is missing in type '{ name: string; columnGroups: { columns: { widgets: undefined[]; }[]; }[]; }' but required in type 'Dashboard'.
```

Note: I've verified that I've followed the steps in the README file to setup the project locally.

**Comment by andrewseguin** [comment]
Thanks - fixed with https://github.com/crafted/crafted/commit/5fdde2f45a19edeb7e1132d740e18aafc77695b2
