### ISSUE TITLE
Document how to setup a Firebase project with GitHub Auth

### ISSUE THREAD

**Issue by EdricChan03** [crafted/crafted#98]
The README should contain instructions for how to setup authentication (steps for creating the GitHub App/OAuth App, creating a Firebase project and specifying the client ID/secret, etc.) for the project.

P.S. I still can't seem to figure out what to do to setup the GitHub app/OAuth app that I would use to authenticate myself to the locally hosted app.

**Comment by EdricChan03** [comment]
It turns out that I'm supposed to create a GitHub OAuth app and specify the client ID and secret for the authentication provider in Firebae Auth.

**Comment by andrewseguin** [comment]
README has been updated with detailed instructions on getting authentication to work
